/**
 * Post-build script: inlines all CSS and JS assets from dist/index.html
 * into a single self-contained HTML file (dist/standalone.html).
 *
 * Also generates src/standaloneTemplate.ts so the app can export
 * interactive maps at runtime.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BASE_PATH = '/2d-star-system-map/';

const distDir = resolve(__dirname, '../dist');
const srcDir = resolve(__dirname, '../src');

const indexPath = resolve(distDir, 'index.html');
if (!existsSync(indexPath)) {
  console.error('dist/index.html not found. Run vite build first.');
  process.exit(1);
}

let html = readFileSync(indexPath, 'utf-8');

// Inline CSS links
const cssLinkRegex = /<link[^>]+rel="stylesheet"[^>]+href="([^"]+)"[^>]*>/g;
let match;
while ((match = cssLinkRegex.exec(html)) !== null) {
  const href = match[1];
  const relativeHref = href.startsWith(BASE_PATH) ? href.slice(BASE_PATH.length) : href.startsWith('/') ? href.slice(1) : href;
  const cssPath = resolve(distDir, relativeHref);
  if (existsSync(cssPath)) {
    const css = readFileSync(cssPath, 'utf-8');
    html = html.replace(match[0], `<style>\n${css}\n</style>`);
    console.log(`  inlined CSS: ${href}`);
  } else {
    console.warn(`  CSS not found: ${cssPath}`);
  }
}

// Inline JS module scripts
const jsScriptRegex = /<script[^>]+type="module"[^>]+src="([^"]+)"[^>]*><\/script>/g;
while ((match = jsScriptRegex.exec(html)) !== null) {
  const src = match[1];
  const relativeSrc = src.startsWith(BASE_PATH) ? src.slice(BASE_PATH.length) : src.startsWith('/') ? src.slice(1) : src;
  const jsPath = resolve(distDir, relativeSrc);
  if (existsSync(jsPath)) {
    const js = readFileSync(jsPath, 'utf-8');
    html = html.replace(match[0], `<script type="module">\n${js}\n</script>`);
    console.log(`  inlined JS: ${src}`);
  } else {
    console.warn(`  JS not found: ${jsPath}`);
  }
}

// Inline modulepreload polyfill if present
const preloadRegex = /<link[^>]+rel="modulepreload"[^>]+href="([^"]+)"[^>]*>/g;
while ((match = preloadRegex.exec(html)) !== null) {
  const href = match[1];
  const relativeHref2 = href.startsWith(BASE_PATH) ? href.slice(BASE_PATH.length) : href.startsWith('/') ? href.slice(1) : href;
  const jsPath = resolve(distDir, relativeHref2);
  if (existsSync(jsPath)) {
    const js = readFileSync(jsPath, 'utf-8');
    // Replace preload link with inline script (modulepreload is just a hint)
    html = html.replace(match[0], `<script type="module">\n${js}\n</script>`);
    console.log(`  inlined preload JS: ${href}`);
  } else {
    html = html.replace(match[0], '');
    console.warn(`  Removed missing preload: ${href}`);
  }
}

// Remove any remaining preload links
html = html.replace(/<link[^>]+rel="modulepreload"[^>]*>/g, '');

// Write standalone HTML
const standalonePath = resolve(distDir, 'standalone.html');
writeFileSync(standalonePath, html);
console.log(`\n✅ Standalone HTML written to ${standalonePath}`);
console.log(`   Size: ${(html.length / 1024).toFixed(1)} KB`);

// Generate TypeScript template module
const templateTs = `// Auto-generated by scripts/inline-build.js
// This is the self-contained standalone HTML template for interactive map export.
// Do not edit manually — run \\"npm run build\\" to regenerate.

export const STANDALONE_TEMPLATE = ${JSON.stringify(html)};
`;

const templatePath = resolve(srcDir, 'standaloneTemplate.ts');
writeFileSync(templatePath, templateTs);
console.log(`✅ Template module written to ${templatePath}`);
